apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: A list of comma separated categories that your operator falls under.
    certified: 'false'
    containerImage: quay.io/app-sre/managed-upgrade-operator:GENERATED
    createdAt: '2023-12-05T07:51:07Z'
    description: Operator providing managed upgrades for OpenShift 4
    support: Red Hat OpenShift SRE
  name: managed-upgrade-operator.v0.1.985-339b161
  namespace: placeholder
spec:
  customresourcedefinitions:
    owned:
    - description: UpgradeConfig
      displayName: UpgradeConfig
      kind: UpgradeConfig
      name: upgradeconfigs.upgrade.managed.openshift.io
      version: v1alpha1
  description: Operator providing managed upgrades for OpenShift 4
  displayName: managed-upgrade-operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - pods/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ''
          resources:
          - events
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - upgrade.managed.openshift.io
          resources:
          - upgradeconfigs
          - upgrade
          - upgradeconfigs/status
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - clusterversions
          - clusteroperators
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.openshift.io
          resources:
          - infrastructures
          verbs:
          - get
          - list
        - apiGroups:
          - machine.openshift.io
          resources:
          - machines
          - machinesets
          verbs:
          - create
          - delete
          - get
          - list
        - apiGroups:
          - machineconfiguration.openshift.io
          resources:
          - machineconfigpools
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - operators.coreos.com
          resources:
          - subscriptions
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - update
          - get
          - list
          - patch
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - fileintegrity.openshift.io
          resources:
          - fileintegrities
          verbs:
          - get
          - update
        serviceAccountName: managed-upgrade-operator
      deployments:
      - name: managed-upgrade-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: managed-upgrade-operator
          template:
            metadata:
              labels:
                name: managed-upgrade-operator
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: node-role.kubernetes.io/master
                        operator: In
                        values:
                        - ''
              containers:
              - command:
                - managed-upgrade-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: managed-upgrade-operator
                - name: OPERATOR_IMAGE
                  value: quay.io/app-sre/managed-upgrade-operator@sha256:ea63be74e12c62499245e5dc606578074f4395a82bc809a722dccd6b1d9bb202
                image: quay.io/app-sre/managed-upgrade-operator@sha256:ea63be74e12c62499245e5dc606578074f4395a82bc809a722dccd6b1d9bb202
                imagePullPolicy: Always
                name: managed-upgrade-operator
                resources:
                  limits:
                    cpu: 50m
                    memory: 200Mi
                  requests:
                    cpu: 20m
                    memory: 100Mi
                volumeMounts:
                - mountPath: /etc/pki/ca-trust/extracted/pem
                  name: trusted-ca-bundle
                  readOnly: true
              serviceAccountName: managed-upgrade-operator
              tolerations:
              - effect: NoSchedule
                key: node-role.kubernetes.io/master
              - effect: NoExecute
                key: node-role.kubernetes.io/master
              volumes:
              - configMap:
                  defaultMode: 420
                  items:
                  - key: ca-bundle.crt
                    path: tls-ca-bundle.pem
                  name: trusted-ca-bundle
                name: trusted-ca-bundle
      permissions: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kubernetes
  - openshift
  - multi-cluster
  - cluster
  links:
  - url: https://github.com/openshift/managed-upgrade-operator
  maintainers:
  - name: OpenShift SRE
  maturity: alpha
  provider:
    name: Red Hat, Inc
  replaces: managed-upgrade-operator.v0.1.973-75b87ea
  version: 0.1.985-339b161
